
api_key = app_store_connect_api_key(
  key_id: "2AZW84W9F8",
  issuer_id: "92de2dbf-bdb7-4b4f-a675-b7a490f651f0",
  key_filepath: "fastlane/AuthKey_2AZW84W9F8.p8",
  duration: 1200,
  in_house: false
)


# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :staging do
    ENV["APP_ENV"] = "STAGING"

    build_app(
      scheme: "golfWaze",
      export_method: "app-store"
    )

    upload_to_testflight(
      distribute_external: true,
      groups: ["External Testers"],
      changelog: "Staging build from CI/CD"
    )
  end

  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end
