api_key = app_store_connect_api_key(
  key_id: "2AZW84W9F8",
  issuer_id: "92de2dbf-bdb7-4b4f-a675-b7a490f651f0",
  key_filepath: "fastlane/AuthKey_2AZW84W9F8.p8",
  duration: 1200,
  in_house: false
)

default_platform(:ios)

platform :ios do

  # ---------- Helper ----------
  def build_changelog
    env = ENV["APP_ENV"] || "STAGING"
    commit = last_git_commit
    message = commit ? commit[:message].split("\n").first : "No commit message"
    "#{env} - #{message}"
  end

  # ---------- STAGING ----------
  lane :staging do
    ENV["APP_ENV"] = "STAGING"

    increment_build_number

    build_app(
      scheme: "golfWaze",
      export_method: "app-store"
    )

    upload_to_testflight(
      api_key: api_key,
      distribute_external: true,
      groups: ["External Testers"],
      changelog: build_changelog
    )
  end

end
